### Lizenz/ Version

Diese Folien wurden von Norman Markgraf zusammen mit Kolleg\*innen von der FOM [https://www.fom.de/](https://www.fom.de/) entwickelt und stehen unter der Lizenz CC-BY-NC-SA 4.0: [https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.de](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.de).

Der verwendete Code sowie das Beamer Template aus dem [NPBT-Projekt](http://github.com/NMarkgraf/NPBT) von Norman Markgraf stehen unter der Lizenz [GNU General Public License v3.0](https://www.gnu.org/licenses/gpl-3.0.de.html).

::: {.footnotesize}

- Datum erstellt: `r Sys.Date()`
- R Version: `r getRversion()` mit `mosaic` Version: `r packageVersion("mosaic")`
- Übersetzt mit den R Packeten:
- knitr Version `r packageVersion("knitr")`, rmarkdown Version `r packageVersion("rmarkdown")`
- pandoc Version :`r rmarkdown::pandoc_version()`
- Python: `r reticulate::py_config()$version_string` mit dem Paket *numpy*: `r reticulate::py_config()$numpy$version`

:::

Bitte melden Sie Fehler und Verbesserungsvorschläge: [nmarkgraf@hotmail.com](<mailto:nmarkgraf@hotmail.com>)

Mitarbeit und Hinweise erwünscht!

**Vielen Dank!**
